version: 2
updates:
  # Enable version updates for Cargo (Rust)
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "sunsided"

  # Enable version updates for npm (React app)
  - package-ecosystem: "npm"
    directory: "/react-app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - "sunsided"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    assignees:
      - "sunsided"
